### ISSUE TITLE
compiler error on ubuntu 18.04

### ISSUE THREAD

**Issue by litongjava** [jonashackt/spring-boot-graalvm#24]
base info
os:ubuntu 18.04
java-version:GraalVM Version 20.2.0 (Java Version 11.0.8)
error log
```
[root@litong-Inspiron-3458 spring-boot-graalvm-master]# ./compile.sh 
[-->] Detect artifactId from pom.xml
artifactId is 'spring-boot-graal'
[-->] Detect artifact version from pom.xml
artifact version is '0.0.1-SNAPSHOT'
[-->] Detect Spring Boot Main class ('start-class') from pom.xml
Spring Boot Main class ('start-class') is 'io.jonashackt.springbootgraal.SpringBootHelloApplication'
[-->] Cleaning target directory & creating new one
[-->] Build Spring Boot App with mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-boot-graal 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ spring-boot-graal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /root/dev_workspace/java/spring-boot-graalvm-master/src/main/resources
[INFO] skip non existing resourceDirectory /root/dev_workspace/java/spring-boot-graalvm-master/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ spring-boot-graal ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /root/dev_workspace/java/spring-boot-graalvm-master/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ spring-boot-graal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /root/dev_workspace/java/spring-boot-graalvm-master/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ spring-boot-graal ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /root/dev_workspace/java/spring-boot-graalvm-master/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ spring-boot-graal ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ spring-boot-graal ---
[INFO] Building jar: /root/dev_workspace/java/spring-boot-graalvm-master/target/spring-boot-graal-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.4.0-M2:repackage (repackage) @ spring-boot-graal ---
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.390 s
[INFO] Finished at: 2020-09-17T22:14:09+08:00
[INFO] Final Memory: 32M/120M
[INFO] ------------------------------------------------------------------------
[-->] Expanding the Spring Boot fat jar
[-->] Set the classpath to the contents of the fat jar (where the libs contain the Spring Graal AutomaticFeature)
[-->] Compiling Spring Boot App 'spring-boot-graal' with GraalVM Version 20.2.0 (Java Version 11.0.8)
[spring-boot-graal:25193]    classlist:  10,755.48 ms,  0.92 GB
   ____         _             _____              ___   ____  ___
  / __/__  ____(_)__  ___ _  / ___/______ ____ _/ / | / /  |/  /
 _\ \/ _ \/ __/ / _ \/ _ `/ / (_ / __/ _ `/ _ `/ /| |/ / /|_/ / 
/___/ .__/_/ /_/_//_/\_, /  \___/_/  \_,_/\_,_/_/ |___/_/  /_/  
   /_/__     __  _  /___/                                       
  / |/ /__ _/ /_(_)  _____ 
 /    / _ `/ __/ / |/ / -_)
/_/|_/\_,_/\__/_/|___/\__/ 
                           
Removing unused configurations
Removing Yaml support
Removing XML support
Removing JMX support
Use -Dspring.native.verbose=true on native-image call to see more detailed information from the feature
FM: mode not set, searching for resources...
[spring-boot-graal:25193]        (cap):   1,354.87 ms,  0.93 GB
Inferred feature operating mode: reflection
Found #15 types in static reflection list to register
Skipping #6 types not on the classpath
Attempting proxy registration of #19 proxies
Skipped registration of #16 proxies - relevant types not on classpath
[spring-boot-graal:25193]        setup:   3,890.54 ms,  0.93 GB
Configuring initialization time for specific types and packages:
#134 buildtime-init-classes   #22 buildtime-init-packages   #18 runtime-init-classes    #0 runtime-init-packages

Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.
Warning: class initialization of class org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory failed with exception java.lang.NoClassDefFoundError: org/apache/coyote/UpgradeProtocol. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory to explicitly request delayed initialization of this class.
Registering statically declared resources - #0 patterns
Registering resources - #0 bundles
Processing META-INF/spring.factories files...
spring.factories processing, problem adding access for key org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer: javax/validation/ValidationException
spring.factories processing, problem adding access for key org.springframework.boot.liquibase.LiquibaseChangelogMissingFailureAnalyzer: liquibase/exception/ChangeLogParseException
Processing spring.factories - PropertySourceLoader lists #1 property source loaders
spring.factories processing, problem adding access for key org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer: org/springframework/jdbc/CannotGetJdbcConnectionException
Processing spring.factories - EnableAutoConfiguration lists #130 configurations
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Excluding 108 auto-configurations from spring.factories file
Including hint not targeting config (trigger=org.springframework.context.annotation.Conditional): CompilationHint for org.springframework.context.annotation.Conditional:{}
Including hint not targeting config (trigger=org.springframework.context.annotation.Import): CompilationHint for org.springframework.context.annotation.Import:{}
Processing existing META-INF/spring.components files...
Registered 3 entries
Registered 0 entries
Number of types dynamically registered for reflective access: #1355
22:14:33.121 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
22:14:33.158 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
22:14:33.159 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
22:14:33.293 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
22:14:33.293 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
22:14:33.294 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
22:14:33.295 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
22:14:33.298 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
22:14:33.299 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:227)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:559)
	at io.netty.handler.codec.http.HttpResponseStatus.newStatus(HttpResponseStatus.java:326)
	at io.netty.handler.codec.http.HttpResponseStatus.<clinit>(HttpResponseStatus.java:39)
	at io.netty.handler.codec.http.HttpObjectAggregator.<clinit>(HttpObjectAggregator.java:90)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:177)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:594)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:130)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:168)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:236)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:271)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:270)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.getEnclosingType(AnalysisType.java:987)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:310)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:169)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:270)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:76)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:52)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:49)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:84)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:47)
	at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:560)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:217)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:188)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:178)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:373)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
	at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:415)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
22:14:33.306 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
22:14:33.306 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @4f164710
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:347)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:338)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:559)
	at io.netty.handler.codec.http.HttpResponseStatus.newStatus(HttpResponseStatus.java:326)
	at io.netty.handler.codec.http.HttpResponseStatus.<clinit>(HttpResponseStatus.java:39)
	at io.netty.handler.codec.http.HttpObjectAggregator.<clinit>(HttpObjectAggregator.java:90)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:177)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:594)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:130)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:168)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:236)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:271)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:270)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.getEnclosingType(AnalysisType.java:987)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:310)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:169)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:270)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:76)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:52)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:49)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:84)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:47)
	at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:560)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:217)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:188)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:178)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:373)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
	at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:415)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
22:14:33.314 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
22:14:33.314 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
22:14:33.317 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 3817865216 bytes (maybe)
22:14:33.317 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
22:14:33.317 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
22:14:33.318 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
22:14:33.318 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
22:14:33.319 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
22:14:33.319 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
22:14:33.321 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
22:14:33.322 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
22:14:48.717 [ForkJoinPool-4-worker-3] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
22:14:48.717 [ForkJoinPool-4-worker-3] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
22:14:48.718 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@3bd26e9b
22:14:48.938 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
22:14:48.938 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
22:14:48.938 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
22:14:48.939 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
22:14:48.939 [ForkJoinPool-4-worker-3] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
22:14:55.027 [ForkJoinPool-2-worker-3] DEBUG io.netty.buffer.AdvancedLeakAwareByteBuf - -Dio.netty.leakDetection.acquireAndReleaseOnly: false
Warning: class initialization of class io.netty.util.internal.logging.Log4JLogger failed with exception java.lang.NoClassDefFoundError: org/apache/log4j/Priority. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger to explicitly request delayed initialization of this class.
22:15:01.343 [ForkJoinPool-2-worker-3] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
22:15:01.354 [ForkJoinPool-2-worker-3] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
22:15:10.358 [ForkJoinPool-2-worker-7] DEBUG io.netty.handler.codec.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibDecoder: false
22:15:10.358 [ForkJoinPool-2-worker-7] DEBUG io.netty.handler.codec.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibEncoder: false
22:15:18.623 [ForkJoinPool-2-worker-1] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
22:15:19.843 [ForkJoinPool-2-worker-5] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
Warning: class initialization of class io.netty.handler.ssl.ReferenceCountedOpenSslContext failed with exception java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext to explicitly request delayed initialization of this class.
22:15:20.088 [ForkJoinPool-2-worker-5] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
22:15:20.088 [ForkJoinPool-2-worker-5] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384]
Warning: class initialization of class io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator failed with exception java.lang.NoClassDefFoundError: org/eclipse/jetty/npn/NextProtoNego$Provider. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator to explicitly request delayed initialization of this class.
22:15:21.120 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
22:15:22.772 [ForkJoinPool-2-worker-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2289cb31
Warning: class initialization of class io.netty.handler.ssl.ReferenceCountedOpenSslEngine failed with exception java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSL. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.ConscryptAlpnSslEngine failed with exception java.lang.NoClassDefFoundError: org/conscrypt/BufferAllocator. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine failed with exception java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine failed with exception java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine to explicitly request delayed initialization of this class.
Warning: class initialization of class io.netty.handler.ssl.JettyNpnSslEngine failed with exception java.lang.NoClassDefFoundError: org/eclipse/jetty/npn/NextProtoNego$Provider. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.handler.ssl.JettyNpnSslEngine to explicitly request delayed initialization of this class.
22:15:32.835 [ForkJoinPool-2-worker-5] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
22:15:32.836 [ForkJoinPool-2-worker-5] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
22:15:32.836 [ForkJoinPool-2-worker-5] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
[spring-boot-graal:25193]     (clinit):     965.90 ms,  2.31 GB
[spring-boot-graal:25193]   (typeflow):  39,610.46 ms,  2.31 GB
[spring-boot-graal:25193]    (objects):  37,254.90 ms,  2.31 GB
[spring-boot-graal:25193]   (features):   4,954.32 ms,  2.31 GB
[spring-boot-graal:25193]     analysis:  84,901.27 ms,  2.31 GB
[spring-boot-graal:25193]     universe:   2,725.22 ms,  2.31 GB
Error: Image build request failed with exit status 137

real	1m55.503s
user	6m6.020s
sys	0m4.953s
```

**Comment by RajeevKumarMarrapu** [comment]
I'm also getting the same issue. I'm using the Ubuntu 20.04

**Comment by jonashackt** [comment]
@litongjava have a look at this paragraph https://github.com/jonashackt/spring-boot-graalvm#tackling-error-image-build-request-failed-with-exit-status-137-with-the--j-xmx-parameter - your environment doesn't have enough RAM, so you need to use the `-J-Xmx` parameter to limit the RAM used for native image compilation. Try with `-J-Xmx4G` and go down, if the error remains - like `-J-Xmx3G`, `-J-Xmx2G`
